token: lip_tPke0HargEV7ulNKcC50
engines:
  classical:
    dir: ./engines
    name: stockfish-windows-x86-64-avx2.exe
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.5
    uci_options:
      Threads: 8
      Hash: 5000
      Move Overhead: 200
      UseBook: true
  rapid:
    dir: ./engines
    name: stockfish-windows-x86-64-avx2.exe
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.2
    uci_options:
      Threads: 8
      Hash: 4096
      Move Overhead: 200
      UseBook: true
  blitz:
    dir: ./engines
    name: stockfish-windows-x86-64-avx2.exe
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.2
    uci_options:
      Threads: 8
      Hash: 4096
      Move Overhead: 100
      MultiPV: 1
      SyzygyProbeDepth: 1
      UseBook: true
  bullet:
    dir: ./engines
    name: stockfish-windows-x86-64-avx2.exe
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 0.7
    uci_options:
      Threads: 2
      MultiPV: 1
      Hash: 64
      Move Overhead: 10
      UseBook: true
  hyperbullet:
    dir: ./engines
    name: stockfish-windows-x86-64-avx2.exe
    ponder: false
    silence_stderr: false
    move_overhead_multiplier: 0.4  # Less buffer, more time for search
    uci_options:
      Threads: 2                  # 2 is faster for most modern CPUs
      MultiPV: 1
      Hash: 8                     # Tiny cache = faster response
      Move Overhead: 30           # Minimal delay before sending move
      UseBook: false              # Optional: true if small book helps
  variants:
    dir: ./engines
    name: fairy-stockfish-largeboard_x86-64-modern.exe
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1
    uci_options:
      Threads: 8
      Hash: 1500
      Move Overhead: 100
syzygy:
  standard:
    enabled: false
    paths:
      - /path/to/standard/syzygy
    max_pieces: 7
    instant_play: true
  antichess:
    enabled: false
    paths:
      - /path/to/antichess/syzygy
    max_pieces: 6
    instant_play: true
  atomic:
    enabled: false
    paths:
      - /path/to/atomic/syzygy
    max_pieces: 6
    instant_play: true
gaviota:
  enabled: false
  paths:
    - /path/to/gaviota
  max_pieces: 5
opening_books:
  enabled: true
  priority: 500
  books:
    standard:
      selection: best_move
      names:
        - Perfect2023
online_moves:
  opening_explorer:
    enabled: false
    priority: 300
    use_for_variants: false
    min_time: 10
    timeout: 5
    min_games: 5
    only_with_wins: false
    selection: performance
    anti: false
  lichess_cloud:
    enabled: true
    priority: 300
    only_without_book: true
    min_eval_depth: 20
    min_time: 10
    timeout: 5
    max_depth: 16
    max_moves: 1
  chessdb:
    enabled: false
    priority: 100
    min_eval_depth: 10
    min_time: 10
    timeout: 5
    selection: best
  online_egtb:
    enabled: true
    min_time: 30
    timeout: 3
offer_draw:
  enabled: true
  score: 20
  consecutive_moves: 5
  min_game_length: 35
  against_humans: false
resign:
  enabled: false
  score: -500
  consecutive_moves: 10
  against_humans: false
challenge:
  concurrency: 1
  bullet_with_increment_only: false
  variants:
    - standard
    - chess960
    - antichess
    - king of the hill
    - atomic 
    - horde 
    - crazyhouse
  time_controls:
    - bullet
    - blitz
    - rapid
  bot_modes:
    - casual
    - rated
  human_modes:
    - casual
    - rated
matchmaking:
  delay: 5
  timeout: 20
  selection: weighted_random
  types:
    bullet:
      tc: "1+0"  # Change this to a single string
    blitz:
      tc: "3+0"  # Change this to a single string
    rapid:
      tc: "10+0"  # Change this to a single string
    classical:
      tc: "30+0"  # Change this to a single string
    chess960:
      tc: "3+2"  # Change this to a single string
      rated: true
messages:
  greeting: 🔥 " {me} has emerged from the quantum void, activating Feynman’s
    neural chess algorithms and engaging the Kasparov-Hawking Paradox — {engine}
    vs {opponent}, prepare for a hyperdimensional battle where spacetime bends,
    your pieces collapse into defeat, and checkmate is the only constant!
    🌌♟️🚀"
  goodbye: Simulation terminated. Good game, {opponent} — return when your mind no
    longer collapses under quantum pressure. ♟️🧠🌌
  greeting_spectators: 🌐 Welcome, observers of spacetime! I’m running {engine} —
    tuned to quantum precision. Type !help to glimpse my neural arsenal. 🧠♟️
  goodbye_spectators: 🌀 Transmission complete. Thanks for watching this ripple in
    the chess continuum — until our timelines align again!
books:
  Perfect2023: C:\Users\Admin\Downloads\torom-boti\torom-boti\Perfect2023.bin
